DROP TABLE IF EXISTS economic_activities;

CREATE TABLE IF NOT EXISTS economic_activities(
   code        VARCHAR(5) NOT NULL PRIMARY KEY
  ,description VARCHAR(72) NOT NULL
);

INSERT INTO economic_activities (code,description) VALUES ('101-5','Órgão Público do Poder Executivo Federal');
INSERT INTO economic_activities (code,description) VALUES ('102-3','Órgão Público do Poder Executivo Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('103-1','Órgão Público do Poder Executivo Municipal');
INSERT INTO economic_activities (code,description) VALUES ('104-0','Órgão Público do Poder Legislativo Federal');
INSERT INTO economic_activities (code,description) VALUES ('105-8','Órgão Público do Poder Legislativo Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('106-6','Órgão Público do Poder Legislativo Municipal');
INSERT INTO economic_activities (code,description) VALUES ('107-4','Órgão Público do Poder Judiciário Federal');
INSERT INTO economic_activities (code,description) VALUES ('108-2','Órgão Público do Poder Judiciário Estadual');
INSERT INTO economic_activities (code,description) VALUES ('110-4','Autarquia Federal');
INSERT INTO economic_activities (code,description) VALUES ('111-2','Autarquia Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('112-0','Autarquia Municipal');
INSERT INTO economic_activities (code,description) VALUES ('113-9','Fundação Pública de Direito Público Federal');
INSERT INTO economic_activities (code,description) VALUES ('114-7','Fundação Pública de Direito Público Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('115-5','Fundação Pública de Direito Público Municipal');
INSERT INTO economic_activities (code,description) VALUES ('116-3','Órgão Público Autônomo Federal');
INSERT INTO economic_activities (code,description) VALUES ('117-1','Órgão Público Autônomo Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('118-0','Órgão Público Autônomo Municipal');
INSERT INTO economic_activities (code,description) VALUES ('119-8','Comissão Polinacional');
INSERT INTO economic_activities (code,description) VALUES ('121-0','Consórcio Público de Direito Público (Associação Pública)');
INSERT INTO economic_activities (code,description) VALUES ('122-8','Consórcio Público de Direito Privado');
INSERT INTO economic_activities (code,description) VALUES ('123-6','Estado ou Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('124-4','Município');
INSERT INTO economic_activities (code,description) VALUES ('125-2','Fundação Pública de Direito Privado Federal');
INSERT INTO economic_activities (code,description) VALUES ('126-0','Fundação Pública de Direito Privado Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('127-9','Fundação Pública de Direito Privado Municipal');
INSERT INTO economic_activities (code,description) VALUES ('128-7','Fundo Público da Administração Indireta Federal');
INSERT INTO economic_activities (code,description) VALUES ('129-5','Fundo Público da Administração Indireta Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('130-9','Fundo Público da Administração Indireta Municipal');
INSERT INTO economic_activities (code,description) VALUES ('131-7','Fundo Público da Administração Direta Federal');
INSERT INTO economic_activities (code,description) VALUES ('132-5','Fundo Público da Administração Direta Estadual ou do Distrito Federal');
INSERT INTO economic_activities (code,description) VALUES ('133-3','Fundo Público da Administração Direta Municipal');
INSERT INTO economic_activities (code,description) VALUES ('134-1','União');
INSERT INTO economic_activities (code,description) VALUES ('201-1','Empresa Pública');
INSERT INTO economic_activities (code,description) VALUES ('203-8','Sociedade de Economia Mista');
INSERT INTO economic_activities (code,description) VALUES ('204-6','Sociedade Anônima Aberta');
INSERT INTO economic_activities (code,description) VALUES ('205-4','Sociedade Anônima Fechada');
INSERT INTO economic_activities (code,description) VALUES ('206-2','Sociedade Empresária Limitada');
INSERT INTO economic_activities (code,description) VALUES ('207-0','Sociedade Empresária em Nome Coletivo');
INSERT INTO economic_activities (code,description) VALUES ('208-9','Sociedade Empresária em Comandita Simples');
INSERT INTO economic_activities (code,description) VALUES ('209-7','Sociedade Empresária em Comandita por Ações');
INSERT INTO economic_activities (code,description) VALUES ('212-7','Sociedade em Conta de Participação');
INSERT INTO economic_activities (code,description) VALUES ('213-5','Empresário (Individual)');
INSERT INTO economic_activities (code,description) VALUES ('214-3','Cooperativa');
INSERT INTO economic_activities (code,description) VALUES ('215-1','Consórcio de Sociedades');
INSERT INTO economic_activities (code,description) VALUES ('216-0','Grupo de Sociedades');
INSERT INTO economic_activities (code,description) VALUES ('217-8','Estabelecimento, no Brasil, de Sociedade Estrangeira');
INSERT INTO economic_activities (code,description) VALUES ('219-4','Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira');
INSERT INTO economic_activities (code,description) VALUES ('221-6','Empresa Domiciliada no Exterior');
INSERT INTO economic_activities (code,description) VALUES ('222-4','Clube/Fundo de Investimento');
INSERT INTO economic_activities (code,description) VALUES ('223-2','Sociedade Simples Pura');
INSERT INTO economic_activities (code,description) VALUES ('224-0','Sociedade Simples Limitada');
INSERT INTO economic_activities (code,description) VALUES ('225-9','Sociedade Simples em Nome Coletivo');
INSERT INTO economic_activities (code,description) VALUES ('226-7','Sociedade Simples em Comandita Simples');
INSERT INTO economic_activities (code,description) VALUES ('227-5','Empresa Binacional');
INSERT INTO economic_activities (code,description) VALUES ('228-3','Consórcio de Empregadores');
INSERT INTO economic_activities (code,description) VALUES ('229-1','Consórcio Simples');
INSERT INTO economic_activities (code,description) VALUES ('230-5','Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)');
INSERT INTO economic_activities (code,description) VALUES ('231-3','Empresa Individual de Responsabilidade Limitada (de Natureza Simples)');
INSERT INTO economic_activities (code,description) VALUES ('232-1','Sociedade Unipessoal de Advogados');
INSERT INTO economic_activities (code,description) VALUES ('233-0','Cooperativas de Consumo');
INSERT INTO economic_activities (code,description) VALUES ('303-4','Serviço Notarial e Registral (Cartório)');
INSERT INTO economic_activities (code,description) VALUES ('306-9','Fundação Privada');
INSERT INTO economic_activities (code,description) VALUES ('307-7','Serviço Social Autônomo');
INSERT INTO economic_activities (code,description) VALUES ('308-5','Condomínio Edilício');
INSERT INTO economic_activities (code,description) VALUES ('310-7','Comissão de Conciliação Prévia');
INSERT INTO economic_activities (code,description) VALUES ('311-5','Entidade de Mediação e Arbitragem');
INSERT INTO economic_activities (code,description) VALUES ('313-1','Entidade Sindical');
INSERT INTO economic_activities (code,description) VALUES ('320-4','Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras');
INSERT INTO economic_activities (code,description) VALUES ('321-2','Fundação ou Associação Domiciliada no Exterior');
INSERT INTO economic_activities (code,description) VALUES ('322-0','Organização Religiosa');
INSERT INTO economic_activities (code,description) VALUES ('323-9','Comunidade Indígena');
INSERT INTO economic_activities (code,description) VALUES ('324-7','Fundo Privado');
INSERT INTO economic_activities (code,description) VALUES ('325-5','Órgão de Direção Nacional de Partido Político');
INSERT INTO economic_activities (code,description) VALUES ('326-3','Órgão de Direção Regional de Partido Político');
INSERT INTO economic_activities (code,description) VALUES ('327-1','Órgão de Direção Local de Partido Político');
INSERT INTO economic_activities (code,description) VALUES ('328-0','Comitê Financeiro de Partido Político');
INSERT INTO economic_activities (code,description) VALUES ('329-8','Frente Plebiscitária ou Referendária');
INSERT INTO economic_activities (code,description) VALUES ('330-1','Organização Social (OS)');
INSERT INTO economic_activities (code,description) VALUES ('331-0','Demais Condomínios');
INSERT INTO economic_activities (code,description) VALUES ('399-9','Associação Privada');
INSERT INTO economic_activities (code,description) VALUES ('401-4','Empresa Individual Imobiliária');
INSERT INTO economic_activities (code,description) VALUES ('402-2','Segurado Especial');
INSERT INTO economic_activities (code,description) VALUES ('408-1','Contribuinte individual');
INSERT INTO economic_activities (code,description) VALUES ('409-0','Candidato a Cargo Político Eletivo');
INSERT INTO economic_activities (code,description) VALUES ('411-1','Leiloeiro');
INSERT INTO economic_activities (code,description) VALUES ('412-0','Produtor Rural (Pessoa Física)');
INSERT INTO economic_activities (code,description) VALUES ('501-0','Organização Internacional');
INSERT INTO economic_activities (code,description) VALUES ('502-9','Representação Diplomática Estrangeira');
INSERT INTO economic_activities (code,description) VALUES ('503-7','Outras Instituições Extraterritoriais');
